#!/usr/bin/env bash

set -e

LOCATION=$HOME
DOTFILES="${HOME}/.dotfiles"
INSTALLFILES="${HOME}/.config/dot_install"

PROGRAMS=(bash chrome colors desktop docker fzf golang i3wm kubernetes music node vim virtualbox)

for program in ${PROGRAMS[@]}; do
    stow -t "${LOCATION}" -d "${DOTFILES}" "${program}"
    echo "Configuring $program"
done

[ dpkg -s "apt-transport-https" >/dev/null 2>&1 ] || sudo apt-get install -y apt-transport-https

for program in ${PROGRAMS[@]}; do
  [ -x "${INSTALLFILES}"/${program}.sh ] && "${INSTALLFILES}"/${program}.sh
done

echo "Done!"
