#!/usr/bin/env bash

set -e

LOCATION=$HOME
DOTFILES="${HOME}/.dotfiles"
INSTALLFILES="${HOME}/.config/dot_install"

PROGRAMS=(bash colors desktop docker fzf golang i3wm kubernetes music node vim virtualbox)

for program in ${PROGRAMS[@]}; do
    stow -t "${LOCATION}" -d "${DOTFILES}" "${program}"
    echo "Configuring $program"
done

for program in ${PROGRAMS[@]}; do
  [ -x "${INSTALLFILES}"/${program}.sh ] && "${INSTALLFILES}"/${program}.sh
done

echo "Done!"
